### Import data

In [1]:
import pandas as pd

# Load data into pandas DataFrames
path = 'cleaned_csv/'
brands = pd.read_csv(path+'brands_cl.csv')
orderlines = pd.read_csv(path+'orderlines_cl.csv')
orders = pd.read_csv(path+'orders_cl.csv')
products = pd.read_csv(path+'products_cl.csv')

In [2]:
# create copies of the original data
orders_df = orders.copy()
orderlines_df = orderlines.copy()
brands_df = brands.copy()
products_df = products.copy()

In [11]:
#adjust dates again
#orders
orders_df["created_date"] = pd.to_datetime(orders_df["created_date"])

#orderlines
orderlines_df['date'] = pd.to_datetime(orderlines_df['date'])

In [12]:
products_orderline_merge = orderlines_df.merge(products_df, on='sku', how='left')
products_orderline_merge

,id,id_order,product_quantity,sku,unit_price,date,name,desc,price,in_stock,type
0,1119109,299539,1,OTT0133,18.99,2017-01-01 00:07:19,Otterbox iPhone Case Symmetry 2.0 SE / 5s / 5 ...,resistant cover and thin beveled edges for iPh...,34.99,0.0,11865403
1,1119110,299540,1,LGE0043,399.00,2017-01-01 00:19:45,"27UD58-B LG Monitor 27 ""4K UHD DisplayPort",Monitor for gamers and multimedia professional...,429.00,0.0,1296
2,1119111,299541,1,PAR0071,474.05,2017-01-01 00:20:57,Parrot Bebop 2 White + Command FLYPAD and FPV ...,cuadricóptero wireless remote control with 25 ...,699.00,0.0,11905404
3,1119112,299542,1,WDT0315,68.39,2017-01-01 00:51:40,"Blue WD 2TB Hard Drive 35 ""Mac and PC",Internal Hard Drive Western Digital 2TB 3.5-in...,79.00,0.0,12655397
4,1119113,299543,1,JBL0104,23.74,2017-01-01 01:06:38,Gray Bluetooth Speaker JBL GO,Compact Bluetooth Handsfree for iPhone iPad an...,29.90,1.0,5398
...,...,...,...,...,...,...,...,...,...,...,...
293978,1650199,527398,1,JBL0122,42.99,2018-03-14 13:57:25,JBL T450 BT Bluetooth Headset Black,Wireless headphones with folding design with 1...,49.95,1.0,5384
293979,1650200,527399,1,PAC0653,141.58,2018-03-14 13:57:34,Samsung SSD 850 expansion kit EVO 250GB + Data...,SSD upgrade kit 2008-2010 250 GB MacBook and M...,215.98,1.0,1433
293980,1650201,527400,2,APP0698,9.99,2018-03-14 13:57:41,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1.0,1230
293981,1650202,527388,1,BEZ0204,19.99,2018-03-14 13:58:01,"Be.ez LArobe Case Mix Macbook 12 ""Green",Macbook thin sheath 12 inches.,29.99,0.0,13835403
293982,1650203,527401,1,APP0927,13.99,2018-03-14 13:58:36,EarPods Apple Headphones with Remote and Mic (...,EarPods headphones Apple iPhone iPad and iPod ...,35.00,1.0,5384

In [18]:
products_orderline_merge.loc[:,'discount'] = round(products_orderline_merge['price']-products_orderline_merge['unit_price'])
products_orderline_merge.loc[:,'discount_percentage'] = round((products_orderline_merge['discount']/products_orderline_merge['price'])*100)
products_orderline_merge[['price','unit_price','discount','discount_percentage']]

         price  unit_price  discount  discount_percentage
0        34.99       18.99      16.0                 46.0
1       429.00      399.00      30.0                  7.0
2       699.00      474.05     225.0                 32.0
3        79.00       68.39      11.0                 14.0
4        29.90       23.74       6.0                 20.0
...        ...         ...       ...                  ...
293978   49.95       42.99       7.0                 14.0
293979  215.98      141.58      74.0                 34.0
293980   25.00        9.99      15.0                 60.0
293981   29.99       19.99      10.0                 33.0
293982   35.00       13.99      21.0                 60.0

[293983 rows x 4 columns]

In [20]:
products_orderline_merge['discount'].describe()

count    285231.000000
mean         50.649340
std         330.523941
min     -159811.000000
25%           5.000000
50%          16.000000
75%          41.000000
max        7172.000000
Name: discount, dtype: float64

In [24]:
products_orderline_merge.loc[products_orderline_merge['discount']>0].describe()

,id,id_order,product_quantity,unit_price,date,price,in_stock,discount,discount_percentage
count,2.577330e+05,257733.000000,257733.000000,257733.000000,257733,257733.000000,257733.000000,257733.000000,257733.000000
mean,1.404324e+06,422768.417925,1.114696,427.713500,2017-09-24 18:18:21.668098,485.880559,0.554380,58.154637,19.321476
min,1.119109e+06,241319.000000,1.000000,-119.000000,2017-01-01 00:07:19,2.990000,0.000000,1.000000,0.000000
25%,1.271647e+06,366816.000000,1.000000,34.990000,2017-06-20 10:21:47,49.950000,0.000000,8.000000,8.000000
50%,1.421138e+06,431041.000000,1.000000,92.990000,2017-11-22 11:03:39,119.000000,1.000000,19.000000,15.000000
75%,1.537796e+06,481803.000000,1.000000,343.990000,2018-01-04 16:55:38,399.000000,1.000000,50.000000,25.000000
max,1.650203e+06,527401.000000,999.000000,14725.000000,2018-03-14 13:58:36,15339.000000,1.000000,7172.000000,200.000000
std,1.520046e+05,65897.330893,2.960000,817.286678,NaN,911.739404,0.497035,144.024768,16.125599